mage_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
        path('game/<int:game_id>/', views.game, name='game'),
        path('pending_games', views.pending_games, name='pending_games'),
        path('active_games', views.active_games, name='active_games'),
        path('start_game/', views.start_game, name='start_game'),
        path('wait_room/<int:game_id>/', views.wait_room, name='wait_room'),
        path('join_game/<int:game_id>/', views.join_game, name='join_game'),
        
        path('card_details/<int:game_id>/<int:card_id>', views.card_details, name='card_details'),
        # path('play_card_from_hand/<int:game_id>/<int:card_id>', views.card_details, name='play_card_from_hand'),
        
        path('play_card/<int:game_id>/<int:card_id>', views.play_card, name='play_card'),

        path('card_ability/<int:game_id>/<int:card_id>', views.card_ability, name='card_ability'),
        path('card_ability2/<int:game_id>/<int:card_id>', views.card_ability2, name='card_ability2'),
        path('ability_target/<int:game_id>/<int:card_id>', views.ability_target, name='ability_target'),
        
        path('play_diamond/<int:game_id>/<int:card_id>', views.diamond_mine, name='diamond_mine'),
        path('diamond_discard/<int:game_id>/<int:card_id>', views.diamond_discard, name='diamond_discard'),
        path('diamond_draw/<int:game_id>/<int:card_id>', views.diamond_draw, name='diamond_draw'),

        path('play_spade/<int:game_id>/<int:card_id>', views.spade_curse, name='spade_curse'),







]

mage_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mage/', include('mage_app.urls')),
    # path('buy_cards/', include('card_store_app')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('accounts_app.urls')),
]

mage_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

SUITS = [
('s', 'Spade'),
('c', 'Club'),
('d', 'Diamond'),
('h', 'Heart')
]

class Game(models.Model):
	CHOICES = [
		('P', 'Pending'),
		('A', 'Active'),
		('F', 'Finished'),
	]
	PHASES = [
		('I', 'Idle'),
		('R', 'Reset'),
		('M', 'Main'),
	]
	library = models.ManyToManyField('Card', through='Library', related_name='library')
	mine = models.ManyToManyField('Card', related_name='mine')
	discard = models.ManyToManyField('Card', related_name='discard')
	status = models.CharField(max_length=8, choices=CHOICES, default='P')
	phase = models.CharField(max_length=8, choices=PHASES, default='I')
	# duelzone = models.ManyToManyField('Card', through='Duelzone')
	spellzone = models.ManyToManyField('Card', through='Spellzone', blank=True)


class Library(models.Model):
	card = models.ForeignKey('Card', on_delete=models.CASCADE, related_name='library_card')
	game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='library_game')
	index = models.IntegerField()

	class Meta:
		ordering = ['index']


class Spellzone(models.Model):
	card = models.ForeignKey('Card', on_delete=models.CASCADE, related_name='spell_card')
	game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='spell_game')
	player = models.ForeignKey('Player', on_delete=models.CASCADE, related_name='spell_player')


class Duelzone(models.Model):
	card = models.ForeignKey('Card', on_delete=models.CASCADE, related_name='duel_card')
	game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='duel_game')
	player = models.ForeignKey('Player', on_delete=models.CASCADE, related_name='duel_player')


class Player(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='player_user')
	hand = models.ManyToManyField('Card', related_name='player_hand', blank=True)
	health = models.IntegerField(default=30)
	vault = models.IntegerField(default=0)
	game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='players')
	court = models.ManyToManyField('Card', related_name='player_court')


class Card(models.Model):

	suit = models.CharField(choices=SUITS, max_length=7)
	value = models.IntegerField()
	


# class Card(models.Model):
# 	suits = [
# 				('s', 'Spade'),
# 				('c', 'Club'),
# 				('d', 'Diamond'),
# 				('h', 'Heart'),
# 				('r', 'Royal'),
# 				('j', 'Joker'),
# 			]
# 	suit = models.CharField(choices=suits, max_length=7)
# 	value = models.IntegerField()

# 	def make_cards(self, value, suit):
# 		for s in suits:
# 			for v in range(1,10):
# 				spade_cards = Card.objects.get_or_create(value=v, suit=suit[0])
# 		for c in club:
# 			for v in range(1,10):
# 				spade_cards = Card.objects.get_or_create(value=v, suit=suit[0])
# 		for h in heart:
# 			for v in range(1,10):
# 				spade_cards = Card.objects.get_or_create(value=v, suit=suit[0])
# 		for d in daimond:
# 			for v in range(1,10):
# 				spade_cards = Card.objects.get_or_create(value=v, suit=suit[0])
# 		for r in royal:
# 			for v in range(1,3):
# 				spade_cards = Card.objects.get_or_create(value=v, suit=suit[0])
# 		for j in joker:
# 			for v in range(1,2):
# 				spade_cards = Card.objects.get_or_create(value=v, suit=suit[0])
		
# 		def deal_cards(self, game):
# 			temp_library = Card.objects.all()
# 			random.shuffle(list(temp_library))
# 	# add shuffled game deck to the game
# 			for card in temp_library:
# 			game.library.add(card)
# 	# deal out 7 cards per player
# 			for num in range(7):
# 				for player in game.players.all():
# 					card = game.library.first()
# 					game.library.remove(card)
# 					player.hand.add(card)

mage_app/views.py
from django.shortcuts import render, redirect
from .models import Game, Player, Card, SUITS, Library
from django.contrib.auth.models import User
from . import game_logic as gl
from django.db.models import Sum


# Create your views here.


def game(request, game_id):
    game = Game.objects.get(id=game_id)
    mine_total = game.mine.all().aggregate(Sum('value'))
    print(mine_total)
    return render(request, 'game.html', {'game': game, 'mine_total': mine_total['value__sum']})
    
def pending_games(request):
    pending = Game.objects.filter(status='P')
    return render(request, 'pending_games.html', {'pending': pending})

def active_games(request):
    active = Game.objects.filter(status='A')
    return render(request, 'active_games.html', {'active': active})

def start_game(request):
    game = Game.objects.create()
    player = Player.objects.create(user=request.user, game=game)
    return redirect('wait_room', game.id)

def wait_room(request, game_id):
    game = Game.objects.get(id=game_id)
    game_players = game.players.all()
    if game_players.count() > 1:
        # add logic handing out cards to players
        game.status = 'A'
        game.save()
        gl.deal_cards(game) 
        return redirect('game', game.id)
    return render(request, 'wait_room.html', {'game': game})

def join_game(request, game_id):
    game = Game.objects.get(id=game_id)
    player, created = Player.objects.get_or_create(user=request.user, game=game)
    return redirect('wait_room', game_id)

def see_game(request, game_id):
    game = Game.objects.get(id=game_id)
    player = game.players.get(user=request.user)
    return redirect('game', game.id)

def card_details(request, game_id, card_id):
    card = Card.objects.get(id=card_id)
    game = Game.objects.get(id=game_id)
    player = game.players.get(user=request.user)
    if card.suit =='d':
        return render(request, 'play_diamond.html', {'card': card, 'game': game})
    
    if card.suit =='s':
        return render(request, 'play_spade.html', {'card': card, 'game': game})

    return render(request, 'card_details.html', {'card': card, 'game': game})

def cost(card, player):
    if 14 > card.value > 10:
        card_cost = card.value - 10
    else:
        card_cost = card.value
    if card_cost > player.vault:
        print('cost is greater than player.valut')
        #add message that insufficient funds
        return False
    player.vault -= card_cost
    player.save()
    return True


def card_ability(request, game_id, card_id):
    card = Card.objects.get(id=card_id)
    game = Game.objects.get(id=game_id)
    return render(request, 'card_ability.html', {'card': card, 'game': game})

def card_ability2(request, game_id, card_id):
    card = Card.objects.get(id=card_id)
    game = Game.objects.get(id=game_id)
    return render(request, 'card_ability2.html', {'card': card, 'game': game})

def ability_target(request, game_id, card_id):
    card = Card.objects.get(id=card_id)
    game = Game.objects.get(id=game_id)
    zones = ['court', 'life']
    return render(request, 'ability_target.html', {'card': card, 'game': game, 'zones': zones})



def play_card(request, game_id, card_id):
    card = Card.objects.get(id=card_id)
    game = Game.objects.get(id=game_id)
    player = game.players.get(user=request.user)
    if card.suit == 'd':
        print(f'diamond was played: {card.suit} {card.value}')
        return render(request, 'play_diamond.html', {'card': card, 'game': game})

    return render(request, 'play_card.html', {'card': card, 'game': game})


def diamond_mine(request, game_id, card_id):
    card = Card.objects.get(id=card_id)
    game = Game.objects.get(id=game_id)
    player = game.players.get(user=request.user)
    # if card.suit =='d':
    player.hand.remove(card)
    game.mine.add(card)
    return redirect('game', game.id)

def diamond_discard(request, game_id, card_id):
    card = Card.objects.get(id=card_id)
    game = Game.objects.get(id=game_id)
    player = game.players.get(user=request.user)
    player.hand.remove(card)
    game.discard.add(card)
    # vault += Player.objects.get(vault=vault)
    return redirect('game', game.id)


def diamond_draw(request, game_id, card_id):
    card = Card.objects.get(id=card_id)
    game = Game.objects.get(id=game_id)
    player = game.players.get(user=request.user)
    player.hand.remove(card)
    game.discard.add(card)
    new_card = Library.objects.filter(game=game).first().card
    game.library.remove(new_card)
    player.hand.add(new_card)
    return redirect('game', game.id)

def spade_curse(request, game_id, card_id):
    card = Card.objects.get(id=card_id)
    game = Game.objects.get(id=game_id)
    player = game.players.get(user=request.user)

    if cost(card,player):
        print('passed cost')
        player.hand.remove(card)
        game.discard.add(card)
        player2 = game.players.exclude(user=request.user).first()
        player2.health -= card.value
        player2.save()
    return redirect('game', game.id)

            







    # library = Library.objects.get(id=library_id)
    # # card_draw = game.library.get(library_card=card).first()
    # # card_draw = Library.objects.filter(library_card=card)
    # card_draw = Library.objects.index[0]
    # game.library.remove(card_draw)
    # player.hand.add(card_draw)






# def play_from_hand(card_id, game_id):
# 	game = Game.objects.get(id=game_id)
# 	card = Card.objects.get(id=card_id)
# 	player = game.players.get(user=request.user)
# 	if 10 < card.value < 14 :
# 		cost = card.value -10 
# 		if player.vault >= cost:
# 			player.vault -= cost		
# 			player.hand.remove(card)
# 			player.court.add(card)
# 			# success flash message?
# 		else:
# 			#add flash messages that user didnt have enough in his valut to play this card
# 			pass
# 	else:
# 		if card.suit == 'd':
# 			return redirect('play_diamond', card.id)
# 		if card.suit in ['s','h','c']:
# 			if player.vault >= card.value:
# 				player.vault -= cost		
# 				player.hand.remove(card)
# 				player.spellzone.add(card)
# 				# success flash message?
# 			else:
# 				#add flash messages that user didnt have enough in his valut to play this card
# 				pass
# 	return redirect('game')





# def play_card_from_hand(request, game_id, card_id):


# def play_from_hand(card_id, game_id):
# 	game = Game.objects.get(id=game_id)
# 	card = Card.objects.get(id=card_id)
# 	player = game.players.get(user=request.user)
#     if card.suit == 'd':
#     return render(request, 'play_diamond.html', {'card': card, 'game': game})
#     return redirect('card_ability')
    


# 	if 10 < card.value < 14 :
# 		cost = card.value -10 
# 		if player.vault >= cost:
# 			player.vault -= cost		
# 			player.hand.remove(card)
# 			player.court.add(card)
# 			# success flash message?
# 		else:
# 			#add flash messages that user didnt have enough in his valut to play this card
# 			pass
# 	else:
# 		if card.suit == 'd':
# 			return redirect('play_diamond', card.id)
# 		if card.suit in ['s','h','c']:
# 			if player.vault >= card.value:
# 				player.vault -= cost		
# 				player.hand.remove(card)
# 				player.spellzone.add(card)
# 				# success flash message?
# 			else:
# 				#add flash messages that user didnt have enough in his valut to play this card
# 				pass
# 	return redirect('game')

# def play_diamond(request, card_id, game_id):
#     game = Game.objects.get(id=game_id)
#     card = Card.objects.get(id=card_id)
#     player = game.players.get(user=request.user)
#     return render(request, 'play_diamond.html', {'card': card, 'game': game})

mage_app/templates/partials/chart_bottom.html
{% extends "game.html" %}
{% block content %}




<div class="container" style="border-color:  rgb(0, 0, 0); border-style: double;">

	<div class="row">
		<div class="col-2" style="border-color:  rgb(0, 0, 0); border-style: double; padding: 2px;">
			<h3>Vault</h3>
		</div>
		<div class="col-1" style="border-color:   rgb(0, 0, 0); border-style: double; padding: 2px;">
			<h3>{{player.vault}}</h3>
		</div>
		<div class="col-2" style="border-color:   rgb(0, 0, 0); border-style: double; padding: 2px;">
			<h3>Court</h3>
		</div>
		<div class="col-7" style="border-color:   rgb(0, 0, 0); border-style: double; padding: 2px;">
			<h3>{{player.court.all}}</h3>
		</div>
	</div>

	<div class="row">
		<div class="col-2" style="border-color:   rgb(0, 0, 0); border-style: double; padding: 2px;">
			<h3>Life</h3>
		</div>
		<div class="col-1" style="border-color:   rgb(0, 0, 0); border-style: double; padding: 2px;">
			<h3>{{player.health}}</h3>
		</div>
		<div class="col-2" style="border-color:   rgb(0, 0, 0); border-style: double; padding: 2px;">
			<h3>Hand</h3>
        </div>
        <div class="col-7" style="border-color:   rgb(0, 0, 0); border-style: double; padding: 2px;">
			<h3>{%for card in player.hand.all%}  <a href='{% url "card_details" game.id card.id %}' class='btn btn-success'>{{card.value}}{{ card.get_suit_display}} {%endfor%}</a></h3>

		</div>
	</div>

	<div class="row">
		<div class="col-2" style="border-color:   rgb(0, 0, 0); border-style: double; padding: 2px;">
			<h3>Phase</h3>
		</div>
		<div class="col-1" style="border-color:   rgb(0, 0, 0); border-style: double; padding: 2px;">
			<h3>{{game.get_phase_display}}</h3>
		</div>
		<div class="col-2" style="border-color:   rgb(0, 0, 0); border-style: double; padding: 2px;">
			<h3>Spell</h3>
		</div>
		<div class="col-7" style="border-color:   rgb(0, 0, 0); border-style: double; padding: 2px;">
			<h3>{{game.spellzone.all}}</h3>
		</div>
	</div>
</div>

{% endblock content %}

mage_app/templates/partials/chart_mid.html
{% extends "game.html" %}
{% block content %}




<div class="container" style="border-color:  black; border-style: double;">

	<div class="row">
		<div class="col-1" style="border-color:  blue; border-style: double; padding: 2px">
			<h3>Mine</h3>
		</div>

		<div class="col-1" style="border-color:  blue; border-style: double; padding: 2px">
			<h3>{{mine_total}}</h3>
		</div>

		<div class="col-1" style="border-color:  blue; border-style: double; padding: 2px">
			<h3>Library</h3>
		</div>

		<div class="col-5" style="border-color:  blue; border-style: double; padding: 2px">
			<h3 class="">{{game.library.count}}</h3>
		</div>
		<div class="col-1" style="border-color:  blue; border-style: double; padding: 2px">
			<h3>Discard</h3>
		</div>
		<div class="col-3" style="border-color:  blue; border-style: double; padding: 2px">
			<h3>{% for card in game.discard.all %}  <a href='{% url "card_details" game.id card.id %}' class='btn btn-success'>{{card.value}}{{ card.get_suit_display}} </a>{%endfor%}</h3>
		</div>
    </div>
</div>


{% endblock content %}

mage_app/templates/partials/chart_top.html
{% extends "game.html" %}
{% block content %}


<div class="container" style="border-color:  red; border-style: double;">

	<div class="row">
		<div class="col-2" style="border-color:  red; border-style: double; padding: 2px">
			<h3>Phase</h3>
		</div>

		<div class="col-1" style="border-color:  red; border-style: double; padding: 2px">
			<h3>{{game.get_phase_display}}</h3>
		</div>

		<div class="col-2" style="border-color:  red; border-style: double; padding: 2px">
			<h3>Spell</h3>
		</div>

		<div class="col-7" style="border-color:  red; border-style: double; padding: 2px">
			<h3>{{game.spellzone.all}}</h3>
		</div>

	</div>

	<div class="row">
		<div class="col-2" style="border-color:  red; border-style: double; padding: 2px">
			<h3>Life</h3>
		</div>

		<div class="col-1" style="border-color:  red; border-style: double; padding: 2px">
			<h3>{{player.health}}</h3>
		</div>

		<div class="col-2" style="border-color:  red; border-style: double; padding: 2px">
			<h3>Hand</h3>
		</div>

		<div class="col-7" style="border-color:  red; border-style: double; padding: 2px">
			<h3>{%for card in player.hand.all%}  <a href='{% url "card_details" game.id card.id %}' class='btn btn-success'>{{card.value}}{{ card.get_suit_display}} {%endfor%}</a></h3>
		</div>
	</div>

	<div class="row">
		<div class="col-2" style="border-color:  red; border-style: double; padding: 2px">
			<h3>Vault</h3>
		</div>

		<div class="col-1" style="border-color:  red; border-style: double; padding: 2px">
			<h3>{{player.vault}}</h3>
		</div>

		<div class="col-2" style="border-color:  red; border-style: double; padding: 2px">
			<h3>Court</h3>
		</div>

		<div class="col-7" style="border-color:  red; border-style: double; padding: 2px">
			<h3>{{player.court.all}}</h3>
		</div>
	</div>
</div>

{% endblock content %}

{% comment %} 
<h3>{%for card in player.hand.all%} <button class='btn btn-danger'>Card {{forloop.counter}}</button> {% endfor %}</h3>

{% endcomment %}